### ISSUE TITLE
[v17] Missing Record when installing 

### ISSUE THREAD

**Issue by rickard-w** [OCA/contract#1135]
When trying to install v17 error is occuring.

> "Missing Record"
Record does not exist or has been deleted.
(Record: sale.subscription.template(6), user: 1)

## Module
Subscription Management

## Describe the bug
Unable to install the module. Error as described above.

## To Reproduce
v17.0.1.0.0
Trying to install on 17.0+e-20240812 (Enterprise Edition)

**Comment by rjpathan** [comment]
module subscription_oca has no error in installing in a new empty database on v17. 

Technically, sale.subscription model has been removed in standard Odoo since odoo v16; so if your database instance has been upgraded from old release prior to v15 then it's possible that sale.subscription table exists in the database with some old data causing the error in installing subscription_oca mod ( that defines same model sale.subscription )
