### ISSUE TITLE
Agreement

### ISSUE THREAD

**Issue by max3903** [OCA/contract#192]
We would like to publish a module to manage content for agreements and contracts. The module is meant to be used by the legal team of a company and to allow them to define sections, clauses and template with their respective content that can be dynamic. Based on the template, an agreement can be created and the pdf document generated. The agreement would go through a workflow to finally become a contract with the customer signature.

Let us know if this repository is not the right place.

**Comment by pedrobaeza** [comment]
I think this one is correct. For the signing, we already have the module contract_digitized_signature.

**Comment by bealdav** [comment]
Hi @max3903,

I've just seen this issue now, and also I see a module named agreement in v11.

I'm very surprised, that you haven't contacted Akretion (@alexis-via or me) about agreement_account and agreement_sale module done in v10.

These modules are really small and easy to override. It could have been a good way to complete them instead of define other implementation or at least ping us to see how to work together on these concepts.

Maybe we can talk to define how to implement the best modularity, on this matter with an RFC ?

Thanks

**Comment by max3903** [comment]
Hi @bealdav,

I understand your frustration. The module we shared was done by our customer as a prototype. The project is not over yet so we still have the opportunity to converge.

**Comment by bealdav** [comment]
Happy to hear that. Maybe we can open an RFC to define changes in v12 branch ? V11 can stay as it.

Thanks

**Comment by max3903** [comment]
Sure!
