### ISSUE TITLE
Unable to duplicate contract with future date_start

### ISSUE THREAD

**Issue by matteotrubini** [OCA/contract#262]
https://github.com/OCA/contract/blob/2fc9eb5fc7053031cd1c0b95eb7b055651d33d3e/contract/models/account_analytic_account.py#L43-L47

On duplicate, `context_today` as default value cause error if you are duplicating a contract that have a future date_start.
Can it defaulted to `date_start`?

**Comment by sbidoul** [comment]
@sbejaoui

**Comment by sbejaoui** [comment]
Hi @matteotrubini , 
We are refactoring the contract module to bring recurrence information to contract line level  #207. It's quite stable and we are using it for 12.0 version.

Otherwise you can port this fix 
https://github.com/OCA/contract/blob/220c28b511544c8a49438741aef0b42044c23342/contract/models/contract_line.py#L32

https://github.com/OCA/contract/blob/220c28b511544c8a49438741aef0b42044c23342/contract/models/contract_line.py#L350-L367

https://github.com/OCA/contract/blob/220c28b511544c8a49438741aef0b42044c23342/contract/models/contract_line.py#L387-L401
