### ISSUE TITLE
[12.0][contract] I cannot select "Account Analytic Group" in "Group" field in Contract

### ISSUE THREAD

**Issue by rafaelbn** [OCA/contract#409]
Hello @sbejaoui 

In Contact -> Tab Other information -> Is the field Group

I guess is for model=account.analytic.group but now it's related to other Account analytic account.

So I cannot use Group in the Group field

See:
![2019-11-02_9-20-01](https://user-images.githubusercontent.com/8736623/68068155-827ebb80-fd52-11e9-955b-250448ad52c7.png)

I think we should fix that.

Maybe I'm missing something/functionality.

Thank you!

**Comment by enricostano** [comment]
I guess the question is why the field is called `group_id` instead of `analytic_account_id`. In v11 the analytic account was at contract level (they were the same thing), but starting from v12 the analytic account is at contract line level.

What's the use case for this `group_id` field? Git history doesn't help much sadly.
