### ISSUE TITLE
[12.0] Contracts for "children partners" are not related in its parent partner Contract Smartbutton.

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/contract#625]
@pedrobaeza 

Use case:

1- Create 1 partner (company).
2- Create a contact for this partner. An invoicing address, for example.
3- Create a contRact for the invoicing contact.

ISSUE:

When you navigate to the parent partner form, you'll see that this partner has 1 contRact related. You'll see a number 1 shown in the smartbutton related to contacts.

When you click to this smartbutton, the contRacts list view is empty as there is a default filter that does not take in consideration the contacts related to the parent partner.

WORKFLOW DESIRED:

Once you click to the smartbutton it should filter contRacts by parent partner and its contacts. Same as is done in sales, invoices...

WDYT?

**Comment by pedrobaeza** [comment]
Change the search view for using `child_of` operator for the filter activated with that smart-button

**Comment by HaraldPanten** [comment]
Sorry Pedro, I don't understand what you mean.

There's no filter activated in the contract search view but a function.

The filter is created by a context. Have a look at res.partner.py

![Captura de pantalla 2021-02-09 a las 13 13 40](https://user-images.githubusercontent.com/32449357/107362320-e0af5800-6ad8-11eb-9d3d-bd61de20da7b.png)

Should we change that?

**Comment by pedrobaeza** [comment]
Yes, there's is, `search_default_partner_id` activates the filter `partner_id` with current id. You should change such filter for using operator `child_of`.

**Comment by manuelregidor** [comment]
I have managed to show the contracts related to a contact and its contact sons when clicking on the smartbutton by returning the ids of the contracts to be shown. The thing is that I would like to apply a filter on the searchbar using the child_of operator when clicking on the smartbutton instead of showing only the contracts related to the contact and its sons. That is the way that it works now with the partner_id filter and I would like to reproduce this behaviour, but I have been trying and I don't know if that is possible or how to get it. Any ideas? Thank you!

**Comment by pedrobaeza** [comment]
Fixed in #634

**Comment by HaraldPanten** [comment]
THX
