### ISSUE TITLE
How to use agreement_legal module on V12 ?

### ISSUE THREAD

**Issue by newtratip** [OCA/contract#632]
I try to play `agreement_legal` module following [README](https://github.com/OCA/contract/blob/12.0/agreement_legal/README.rst) but I didn't understand in some point
 
> **To configure this module:**
> - Go to Agreement > Configuration > Templates
> - Create a new template with sections and clauses and their respective content
> - Go to Agreement > Configuration > Stages
> - Create and reorder stages to match your process
> 
> **To use this module:**
> - Go to Agreement > Agreements
> - Create a new agreement
> - Select a template
> - Follow the process to get the required approval
> - Send the invitation to the customer to review and sign the agreement
> - Define Field using widget domain but having partial_use option true:
> - For Ex:
> - <field name="field_domain" widget="domain" nolabel="1"
> - options="{'model': 'agreement.recital',
> - 'partial_use': True}"/>
 
**My question**
- How can I select template on agreement ?
- What is really objective of Dashboard > Agreements and Operations > Agreement menu
- What is Renewal Types and Increase Types on configuration menu ?

**Comment by marylla** [comment]
@newtratip These are very good questions that I asked myself as well. 

I am using the template as template by copying it. Not very elegant for sure but I couldn't find another solution yet.
Therefore, I also needed to make the "code" (Reference) field not readonly anymore because when copying the template the code was set to "AG001 (Copy)" and I could not change the code anymore. 

And unfortunately, I could not find an answer to your other questions.
Maybe @ygol can help here?
